<a href="https://colab.research.google.com/github/2303A52243/GENERATIVE-AI-2025/blob/main/G_SRISAHITH_2303A52243_WEEK_1_ASS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#TABLE 1
import numpy as np
import math
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

Y_actual = np.array([20, 30, 40, 50, 60])
Y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

mae = np.mean(np.abs(Y_actual - Y_pred))
mse = np.mean((Y_actual - Y_pred)**2)
rmse = math.sqrt(mse)
r2 = r2_score(Y_actual, Y_pred)

print(f"MAE (Manual): {mae}")
print(f"MSE (Manual): {mse}")
print(f"RMSE (Manual): {rmse}")
print(f"R-squared (Manual): {r2}")

print(f"MAE (sklearn): {mean_absolute_error(Y_actual, Y_pred)}")
print(f"MSE (sklearn): {mean_squared_error(Y_actual, Y_pred)}")
print(f"RMSE (sklearn): {math.sqrt(mean_squared_error(Y_actual, Y_pred))}")
print(f"R-squared (sklearn): {r2_score(Y_actual, Y_pred)}")


MAE (Manual): 0.4600000000000016
MSE (Manual): 0.24600000000000147
RMSE (Manual): 0.49598387070549127
R-squared (Manual): 0.99877
MAE (sklearn): 0.4600000000000016
MSE (sklearn): 0.24600000000000147
RMSE (sklearn): 0.49598387070549127
R-squared (sklearn): 0.99877


In [ ]:
#TABLE 2
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, confusion_matrix

Y_actual_class = np.array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 0, 2, 2, 2, 1, 1, 2])
Y_pred_class = np.array([0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 0, 0, 2, 2, 2, 1, 2])

precision = precision_score(Y_actual_class, Y_pred_class, average='weighted', zero_division=1)
recall = recall_score(Y_actual_class, Y_pred_class, average='weighted', zero_division=1)
f1 = f1_score(Y_actual_class, Y_pred_class, average='weighted', zero_division=1)
accuracy = accuracy_score(Y_actual_class, Y_pred_class)
conf_matrix = confusion_matrix(Y_actual_class, Y_pred_class)

print(f"Precision (Manual): {precision}")
print(f"Recall (Manual): {recall}")
print(f"F1-Score (Manual): {f1}")
print(f"Accuracy (Manual): {accuracy}")
print(f"Confusion Matrix (Manual): \n{conf_matrix}")

print(f"Precision (sklearn): {precision_score(Y_actual_class, Y_pred_class, average='weighted', zero_division=1)}")
print(f"Recall (sklearn): {recall_score(Y_actual_class, Y_pred_class, average='weighted', zero_division=1)}")
print(f"F1-Score (sklearn): {f1_score(Y_actual_class, Y_pred_class, average='weighted', zero_division=1)}")
print(f"Accuracy (sklearn): {accuracy_score(Y_actual_class, Y_pred_class)}")
print(f"Confusion Matrix (sklearn): \n{confusion_matrix(Y_actual_class, Y_pred_class)}")


Precision (Manual): 0.7619047619047619
Recall (Manual): 0.76
F1-Score (Manual): 0.7592156862745099
Accuracy (Manual): 0.76
Confusion Matrix (Manual): 
[[8 1 0]
 [0 5 3]
 [1 1 6]]
Precision (sklearn): 0.7619047619047619
Recall (sklearn): 0.76
F1-Score (sklearn): 0.7592156862745099
Accuracy (sklearn): 0.76
Confusion Matrix (sklearn): 
[[8 1 0]
 [0 5 3]
 [1 1 6]]
